### ISSUE TITLE
Inappropriate use of the arduino-library topic

### ISSUE THREAD

**Issue by per1234** [fuzzymannerz/AVR-BASIC-Computer#1]
This repository is not an Arduino library, thus the use of the `arduino-library` topic is inappropriate.

The topic can be removed by clicking the "Manage topics" link near the top of the repository's home page and then clicking the X to the right of `arduino-library`.

**Comment by fuzzymannerz** [comment]
Thanks for the heads up about the topic, I removed it as to not cause any potential confusion in the future. :)

**Comment by per1234** [comment]
Thanks!
