### ISSUE TITLE
Multi-line comment swallows code

### ISSUE THREAD

**Issue by bobc** [fuzzymannerz/AVR-BASIC-Computer#2]
https://github.com/fuzzymannerz/AVR-BASIC-Computer/blob/7b249fcb63225c0e73baa0a06fb459cd93b43ce7/libraries/TVout/TVoutfonts/font4x6.cpp#L426

Putting a back-slash at the end of line creates an escape sequence which swallows the EOL, and creates a multi-line comment, so the next code line is part of the comment.

If you want an actual \ character you should write \\\\.

**Comment by fuzzymannerz** [comment]
Ahh thanks! Never noticed that before, I have changed the comment line. :)
